WS_MSG = lambda type,stat, msg: {
    "TYPE": type,
    "STATUS": stat,
    "MSG": msg
}


REQUEST_TOKEN_MSG_REQ_TYPE = "REQUEST_TOKEN_MSG"
REQUEST_TOKEN_MSG_RES_TYPE = "REQUEST_TOKEN_MSG"
REQUEST_TOKEN_MSG = lambda msgContent="" : WS_MSG(REQUEST_TOKEN_MSG_REQ_TYPE, True, msgContent)

ACCES_GRANTED_MSG_INFO_TYPE = "ACCES_GRANTED_MSG_INFO_TYPE"
ACCES_GRANTED_MSG = WS_MSG(ACCES_GRANTED_MSG_INFO_TYPE, True, "")

ACCES_DENIED_MSG_INFO_TYPE = "ACCES_DENIED_MSG_INFO_TYPE"
ACCES_DENIED_MSG = WS_MSG(ACCES_DENIED_MSG_INFO_TYPE, True, "")
