WS_MSG = lambda type,stat, msg: {
    "TYPE": type,
    "STATUS": stat,
    "MSG": msg
}


REQUEST_TOKEN_MSG_REQ_TYPE = "REQUEST_TOKEN_MSG"
REQUEST_TOKEN_MSG_RES_TYPE = "REQUEST_TOKEN_MSG"
REQUEST_TOKEN_MSG = lambda msgContent="" : WS_MSG(REQUEST_TOKEN_MSG_REQ_TYPE, True, msgContent)

ACCESS_GRANTED_MSG_INFO_TYPE = "ACCESS_GRANTED_MSG_INFO_TYPE"
ACCESS_GRANTED_MSG = WS_MSG(ACCESS_GRANTED_MSG_INFO_TYPE, True, "")

ACCESS_DENIED_MSG_INFO_TYPE = "ACCESS_DENIED_MSG_INFO_TYPE"
ACCESS_DENIED_MSG = WS_MSG(ACCESS_DENIED_MSG_INFO_TYPE, True, "")
