



class WsMessageType:
    REQUEST_TOKEN_MSG_TYPE = "REQUEST_TOKEN_MSG"
    RETURN_TOKEN_MSG_TYPE = "RETURN_TOKEN_MSG"

    ACCESS_GRANTED_MSG_INFO_TYPE = "ACCESS_GRANTED_MSG_INFO_TYPE"
    ACCESS_DENIED_MSG_INFO_TYPE = "ACCESS_DENIED_MSG_INFO_TYPE"
    

    
        