class WsMessageType:
    TOKEN__REQ = "TOKEN_REQ"
    TOKEN__RES = "TOKEN_RES"


    ACCESS_GRANTED__INFO = "ACCESS_GRANTED_INFO"
    ACCESS_DENIED__INFO = "ACCESS_DENIED_INFO"

    RT_MESSAGES_IN_CONVERSATION__REQ = "RT_MESSAGES_IN_CONVERSATION_REQ"
    RT_MESSAGES_IN_CONVERSATION__RES = "RT_MESSAGES_IN_CONVERSATION_RES"

    NEW_CONVERSATION_MSG__DATA = "NEW_CONVERSATION_MSG_DATA"

    requests = [RT_MESSAGES_IN_CONVERSATION__REQ, TOKEN__REQ]
    
